### Create random matrices

In [90]:
a = np.random.rand(3,3)

In [91]:
a

array([[0.83559786, 0.30032856, 0.38185552],
       [0.35859493, 0.25600032, 0.70316501],
       [0.85927853, 0.55535776, 0.19510387]])

In [97]:
np.linalg.inv(a)

array([[-5.,  2.],
       [ 3., -1.]])

In [92]:
b = np.random.randint(100, size=(5, 2))

In [93]:
b

array([[45, 29],
       [46, 39],
       [43, 30],
       [96, 67],
       [29, 73]])

### Solve linear equations using matrices

In [94]:
a = np.array([[1, 2], [3, 5]])
b = np.array([1, 2])

In [95]:
x = np.linalg.solve(a,b)

In [96]:
x

array([-1.,  1.])

### Create array

In [23]:
import numpy as np
a = np.array([[1, 2], [3, 4]])
b = np.array([[5,6], [7,8]])

In [26]:
print(a*b)

[[ 5 12]
 [21 32]]


In [27]:
a3D = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

In [28]:
a3D

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [29]:
x = np.arange(10)

In [43]:
x.shape

(10,)

In [33]:
x[1:7:2]

array([1, 3, 5])

In [38]:
z = np.array([1,2])

In [42]:
z.shape

(2,)

In [54]:
a = np.array([10,3,7,1,0])
np.diff(a)

array([-7,  4, -6, -1])

In [56]:
a = np.arange(20)

In [57]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [62]:
a[15::-1]

array([15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [64]:
a[-3:]

array([17, 18, 19])

In [65]:
y = np.arange(35).reshape(5,7)

In [66]:
y

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34]])

In [67]:
y[1:5:2,::3]

array([[ 7, 10, 13],
       [21, 24, 27]])

In [35]:
import numpy as np
a = np.random.rand(5,2)

In [36]:
a

array([[0.52736968, 0.55707202],
       [0.2741818 , 0.75263641],
       [0.78739927, 0.80273551],
       [0.51898833, 0.26869427],
       [0.38965604, 0.21033776]])

In [37]:
np.shape(a)

(5, 2)

In [45]:
np.shape(b)

(5, 2)

In [46]:
b

array([[ 0, 48],
       [32, 58],
       [21, 56],
       [74, 88],
       [ 9, 36]])

In [47]:
a*b

array([[ 0.        , 26.73945712],
       [ 8.77381758, 43.65291172],
       [16.53538457, 44.95318838],
       [38.40513639, 23.64509614],
       [ 3.50690432,  7.57215938]])

In [53]:
c = np.random.randint(10, size = (5,2))

In [54]:
c

array([[4, 5],
       [9, 1],
       [8, 5],
       [6, 3],
       [9, 6]])

In [56]:
b/c

array([[ 0.        ,  9.6       ],
       [ 3.55555556, 58.        ],
       [ 2.625     , 11.2       ],
       [12.33333333, 29.33333333],
       [ 1.        ,  6.        ]])

In [57]:
b*c

array([[  0, 240],
       [288,  58],
       [168, 280],
       [444, 264],
       [ 81, 216]])

In [59]:
d = np.random.randint(10, size = (2,5))

In [60]:
d

array([[1, 8, 9, 9, 1],
       [3, 0, 3, 2, 0]])

In [61]:
np.shape(d)

(2, 5)

In [63]:
np.matmul(b,d)

array([[144,   0, 144,  96,   0],
       [206, 256, 462, 404,  32],
       [189, 168, 357, 301,  21],
       [338, 592, 930, 842,  74],
       [117,  72, 189, 153,   9]])

In [64]:
d

array([[1, 8, 9, 9, 1],
       [3, 0, 3, 2, 0]])

In [65]:
np.transpose(d)

array([[1, 3],
       [8, 0],
       [9, 3],
       [9, 2],
       [1, 0]])

In [70]:
np.flip(d, axis = 1)

array([[1, 9, 9, 8, 1],
       [0, 2, 3, 0, 3]])

In [71]:
d

array([[1, 8, 9, 9, 1],
       [3, 0, 3, 2, 0]])

In [79]:
e = d.flatten()

In [80]:
e

array([1, 8, 9, 9, 1, 3, 0, 3, 2, 0])

In [82]:
import scipy

In [84]:
x

array([-1.,  1.])

In [88]:
a

array([[0.22129892, 0.62372624, 0.94862358],
       [0.62889514, 0.00140424, 0.0249154 ],
       [0.43715646, 0.46295055, 0.48827397]])

In [89]:
np.linalg.inv(a)

array([[-0.1226284 ,  1.52160536,  0.16059998],
       [-3.34781282, -3.46605873,  6.68102868],
       [ 3.28397511,  1.92398986, -4.4302857 ]])