In [10]:
import numpy as np
nums = [-9, -2, 0, 2, 3]
new_lst = np.sort([num**2 for num in nums])
new_lst

array([ 0,  4,  4,  9, 81])

In [24]:
import numpy as np
def squareSorted(lst):
    new = []
    for i in lst:
        i = i**2
        new.append(i)
    return(np.sort(new))
squareSorted(nums)

array([ 0,  4,  4,  9, 81])

In [25]:
squareSorted(nums)

array([ 0,  4,  4,  9, 81])