In [1]:
def sumTwoNumbers(arr,k):
    for i in range(len(arr)):
        for j in range(i +1, len(arr)):
            total = arr[i] + arr[j];
            if total == k:
                print(arr[i], arr[j])

In [5]:
arr = ([10, 8, 5, 6, 7]);
k = 13;

In [3]:
sumTwoNumbers(arr,k)

8 5
6 7


# LATEX equations
$e^{i\pi} + 1 = 0$

In [6]:
arr[2:3]

[5]

In [8]:
sum(arr[4:10])

7

# Matrix and Array

In [148]:
import numpy as np
a = np.arange(1,11,1)
b = np.arange(11,21,1)

In [58]:
np.

935

In [151]:
np.concatenate((a,b), axis = 1)

AxisError: axis 1 is out of bounds for array of dimension 1

In [66]:
np.argmax(a)

9

In [108]:
a = np.zeros(3)

In [107]:
np.transpose(b)

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [135]:
a = np.empty(shape=(2,3), dtype = object)

In [139]:
a

array([[None, None, None],
       [None, None, 3]], dtype=object)

In [138]:
a[1,2] = 3

In [144]:
c = [None]*5

In [145]:
c

[None, None, None, None, None]

In [146]:
list(c)

[None, None, None, None, None]

In [147]:
np.array(c)

array([None, None, None, None, None], dtype=object)

In [156]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7,8]])

In [160]:
z = np.concatenate((x,y), axis = 1)

In [161]:
print(z)

[[1 2 5 6]
 [3 4 7 8]]


In [164]:
np.shape(z)

(2, 4)

In [165]:
a = np.linspace(1,10,10)

In [190]:
np.ndim(a)

1

In [170]:
np.ndim(a)

1

In [203]:
a1 = np.expand_dims(a, axis = 1)

In [204]:
np.ndim(a1)

2

In [209]:
a1

array([[100.],
       [  2.],
       [  3.],
       [  4.],
       [  5.],
       [  6.],
       [  7.],
       [  8.],
       [  9.],
       [ 10.]])

In [237]:
np.flip(a1)

array([[ 10.],
       [  9.],
       [  8.],
       [  7.],
       [  6.],
       [  5.],
       [  4.],
       [  3.],
       [  2.],
       [100.]])

In [226]:
a1[0,0] = 100

In [210]:
a2 = np.expand_dims(a1, axis = 1)

In [234]:
np.shape(a1)

(10, 1)

In [232]:
np.ndim(a2)

3

In [222]:
np.random.random((2,5))

array([[0.84788911, 0.65465589, 0.70862588, 0.60414089, 0.32875847],
       [0.1618245 , 0.56532385, 0.18125956, 0.68148765, 0.68137265]])

In [219]:
rng.random((3, 2))

NameError: name 'rng' is not defined